server:
  port: 7000
  servlet:
    context-path: /cross-server
spring:
  application:
    name: CROSS_SERVER    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    